-- tts_voice_catalog 테이블의 모든 음성에 한글 이름(name_ko) 업데이트
-- 기존에 name_ko가 없거나 NULL인 경우에만 업데이트

-- 기존 음성 데이터에 한글 이름 일괄 업데이트
-- CASE 문을 사용하여 voice_id에 따라 name_ko 설정

UPDATE public.tts_voice_catalog
SET name_ko = CASE voice_id
  -- 여성 음성
  WHEN 'Agatha' THEN '아가사'
  WHEN 'Alice' THEN '앨리스'
  WHEN 'Amy' THEN '에이미'
  WHEN 'Anna' THEN '안나'
  WHEN 'Aria' THEN '아리아'
  WHEN 'Aurora' THEN '오로라'
  WHEN 'Bella' THEN '벨라'
  WHEN 'Chloe' THEN '클로이'
  WHEN 'Diana' THEN '다이아나'
  WHEN 'Emma' THEN '엠마'
  WHEN 'Eva' THEN '에바'
  WHEN 'Fiona' THEN '피오나'
  WHEN 'Grace' THEN '그레이스'
  WHEN 'Hannah' THEN '한나'
  WHEN 'Iris' THEN '아이리스'
  WHEN 'Ivy' THEN '아이비'
  WHEN 'Jade' THEN '제이드'
  WHEN 'Julia' THEN '줄리아'
  WHEN 'Kate' THEN '케이트'
  WHEN 'Lily' THEN '릴리'
  WHEN 'Luna' THEN '루나'
  WHEN 'Maya' THEN '마야'
  WHEN 'Nora' THEN '노라'
  WHEN 'Olivia' THEN '올리비아'
  WHEN 'Phoebe' THEN '피비'
  WHEN 'Rose' THEN '로즈'
  WHEN 'Sophia' THEN '소피아'
  WHEN 'Stella' THEN '스텔라'
  WHEN 'Tina' THEN '티나'
  WHEN 'Tracy' THEN '트레이시'
  WHEN 'Vera' THEN '베라'
  WHEN 'Violet' THEN '바이올렛'
  WHEN 'Wendy' THEN '웬디'
  WHEN 'Zoe' THEN '조이'
  
  -- 남성 음성
  WHEN 'Alex' THEN '알렉스'
  WHEN 'Andrew' THEN '앤드류'
  WHEN 'Ben' THEN '벤'
  WHEN 'Brian' THEN '브라이언'
  WHEN 'Chris' THEN '크리스'
  WHEN 'Daniel' THEN '다니엘'
  WHEN 'David' THEN '데이비드'
  WHEN 'Dom' THEN '돔'
  WHEN 'Eric' THEN '에릭'
  WHEN 'Ethan' THEN '이단'
  WHEN 'George' THEN '조지'
  WHEN 'Henry' THEN '헨리'
  WHEN 'Jack' THEN '잭'
  WHEN 'James' THEN '제임스'
  WHEN 'John' THEN '존'
  WHEN 'Kevin' THEN '케빈'
  WHEN 'Leo' THEN '레오'
  WHEN 'Lucas' THEN '루카스'
  WHEN 'Mark' THEN '마크'
  WHEN 'Michael' THEN '마이클'
  WHEN 'Noah' THEN '노아'
  WHEN 'Oliver' THEN '올리버'
  WHEN 'Paul' THEN '폴'
  WHEN 'Peter' THEN '피터'
  WHEN 'Robert' THEN '로버트'
  WHEN 'Ryan' THEN '라이언'
  WHEN 'Sam' THEN '샘'
  WHEN 'Thomas' THEN '토마스'
  WHEN 'Timmy' THEN '티미'
  WHEN 'Toby' THEN '토비'
  WHEN 'Toma' THEN '토마'
  WHEN 'Tom' THEN '톰'
  WHEN 'Travis' THEN '트래비스'
  WHEN 'Valiant' THEN '발리언트'
  WHEN 'Victor' THEN '빅터'
  WHEN 'Vince' THEN '빈스'
  WHEN 'William' THEN '윌리엄'
  
  -- 기타 특수 음성
  WHEN 'jiyun' THEN '지윤'
  WHEN 'male_anchor_1' THEN '앵커 스타일 남성 1'
  WHEN 'male_anchor_2' THEN '앵커 스타일 남성 2'
  WHEN 'female_anchor_1' THEN '아나운서 스타일 여성 1'
  WHEN 'female_anchor_2' THEN '아나운서 스타일 여성 2'
  WHEN 'female_weather_1' THEN '기상 아나운서 스타일'
  
  ELSE NULL
END
WHERE (name_ko IS NULL OR name_ko = '' OR name_ko = voice_id);

-- 소문자로 저장된 voice_id도 처리
UPDATE public.tts_voice_catalog
SET name_ko = CASE LOWER(voice_id)
  WHEN 'agatha' THEN '아가사'
  WHEN 'alice' THEN '앨리스'
  WHEN 'amy' THEN '에이미'
  WHEN 'anna' THEN '안나'
  WHEN 'aria' THEN '아리아'
  WHEN 'aurora' THEN '오로라'
  WHEN 'bella' THEN '벨라'
  WHEN 'chloe' THEN '클로이'
  WHEN 'diana' THEN '다이아나'
  WHEN 'emma' THEN '엠마'
  WHEN 'eva' THEN '에바'
  WHEN 'fiona' THEN '피오나'
  WHEN 'grace' THEN '그레이스'
  WHEN 'hannah' THEN '한나'
  WHEN 'iris' THEN '아이리스'
  WHEN 'ivy' THEN '아이비'
  WHEN 'jade' THEN '제이드'
  WHEN 'julia' THEN '줄리아'
  WHEN 'kate' THEN '케이트'
  WHEN 'lily' THEN '릴리'
  WHEN 'luna' THEN '루나'
  WHEN 'maya' THEN '마야'
  WHEN 'nora' THEN '노라'
  WHEN 'olivia' THEN '올리비아'
  WHEN 'phoebe' THEN '피비'
  WHEN 'rose' THEN '로즈'
  WHEN 'sophia' THEN '소피아'
  WHEN 'stella' THEN '스텔라'
  WHEN 'tina' THEN '티나'
  WHEN 'tracy' THEN '트레이시'
  WHEN 'vera' THEN '베라'
  WHEN 'violet' THEN '바이올렛'
  WHEN 'wendy' THEN '웬디'
  WHEN 'zoe' THEN '조이'
  WHEN 'alex' THEN '알렉스'
  WHEN 'andrew' THEN '앤드류'
  WHEN 'ben' THEN '벤'
  WHEN 'brian' THEN '브라이언'
  WHEN 'chris' THEN '크리스'
  WHEN 'daniel' THEN '다니엘'
  WHEN 'david' THEN '데이비드'
  WHEN 'dom' THEN '돔'
  WHEN 'eric' THEN '에릭'
  WHEN 'ethan' THEN '이단'
  WHEN 'george' THEN '조지'
  WHEN 'henry' THEN '헨리'
  WHEN 'jack' THEN '잭'
  WHEN 'james' THEN '제임스'
  WHEN 'john' THEN '존'
  WHEN 'kevin' THEN '케빈'
  WHEN 'leo' THEN '레오'
  WHEN 'lucas' THEN '루카스'
  WHEN 'mark' THEN '마크'
  WHEN 'michael' THEN '마이클'
  WHEN 'noah' THEN '노아'
  WHEN 'oliver' THEN '올리버'
  WHEN 'paul' THEN '폴'
  WHEN 'peter' THEN '피터'
  WHEN 'robert' THEN '로버트'
  WHEN 'ryan' THEN '라이언'
  WHEN 'sam' THEN '샘'
  WHEN 'thomas' THEN '토마스'
  WHEN 'timmy' THEN '티미'
  WHEN 'toby' THEN '토비'
  WHEN 'toma' THEN '토마'
  WHEN 'tom' THEN '톰'
  WHEN 'travis' THEN '트래비스'
  WHEN 'valiant' THEN '발리언트'
  WHEN 'victor' THEN '빅터'
  WHEN 'vince' THEN '빈스'
  WHEN 'william' THEN '윌리엄'
  
  ELSE NULL
END
WHERE (name_ko IS NULL OR name_ko = '' OR name_ko = voice_id);

-- voice_data JSONB에 저장된 name 필드를 name_ko로 사용 (클론 음성 등)
-- voice_data->>'name'이 있고 한글이 포함되어 있으면 그대로 사용
UPDATE public.tts_voice_catalog
SET name_ko = voice_data->>'name'
WHERE (name_ko IS NULL OR name_ko = '' OR name_ko = voice_id)
  AND voice_data->>'name' IS NOT NULL
  AND voice_data->>'name' != ''
  AND (voice_data->>'name' ~ '[가-힣]' OR LENGTH(voice_data->>'name') > 0);

-- voice_data->>'name'이 영어인 경우 한글 매핑 시도
UPDATE public.tts_voice_catalog
SET name_ko = CASE LOWER(voice_data->>'name')
  WHEN 'agatha' THEN '아가사'
  WHEN 'alice' THEN '앨리스'
  WHEN 'amy' THEN '에이미'
  WHEN 'anna' THEN '안나'
  WHEN 'aria' THEN '아리아'
  WHEN 'aurora' THEN '오로라'
  WHEN 'bella' THEN '벨라'
  WHEN 'chloe' THEN '클로이'
  WHEN 'diana' THEN '다이아나'
  WHEN 'emma' THEN '엠마'
  WHEN 'eva' THEN '에바'
  WHEN 'fiona' THEN '피오나'
  WHEN 'grace' THEN '그레이스'
  WHEN 'hannah' THEN '한나'
  WHEN 'iris' THEN '아이리스'
  WHEN 'ivy' THEN '아이비'
  WHEN 'jade' THEN '제이드'
  WHEN 'julia' THEN '줄리아'
  WHEN 'kate' THEN '케이트'
  WHEN 'lily' THEN '릴리'
  WHEN 'luna' THEN '루나'
  WHEN 'maya' THEN '마야'
  WHEN 'nora' THEN '노라'
  WHEN 'olivia' THEN '올리비아'
  WHEN 'phoebe' THEN '피비'
  WHEN 'rose' THEN '로즈'
  WHEN 'sophia' THEN '소피아'
  WHEN 'stella' THEN '스텔라'
  WHEN 'tina' THEN '티나'
  WHEN 'tracy' THEN '트레이시'
  WHEN 'vera' THEN '베라'
  WHEN 'violet' THEN '바이올렛'
  WHEN 'wendy' THEN '웬디'
  WHEN 'zoe' THEN '조이'
  WHEN 'alex' THEN '알렉스'
  WHEN 'andrew' THEN '앤드류'
  WHEN 'ben' THEN '벤'
  WHEN 'brian' THEN '브라이언'
  WHEN 'chris' THEN '크리스'
  WHEN 'daniel' THEN '다니엘'
  WHEN 'david' THEN '데이비드'
  WHEN 'dom' THEN '돔'
  WHEN 'eric' THEN '에릭'
  WHEN 'ethan' THEN '이단'
  WHEN 'george' THEN '조지'
  WHEN 'henry' THEN '헨리'
  WHEN 'jack' THEN '잭'
  WHEN 'james' THEN '제임스'
  WHEN 'john' THEN '존'
  WHEN 'kevin' THEN '케빈'
  WHEN 'leo' THEN '레오'
  WHEN 'lucas' THEN '루카스'
  WHEN 'mark' THEN '마크'
  WHEN 'michael' THEN '마이클'
  WHEN 'noah' THEN '노아'
  WHEN 'oliver' THEN '올리버'
  WHEN 'paul' THEN '폴'
  WHEN 'peter' THEN '피터'
  WHEN 'robert' THEN '로버트'
  WHEN 'ryan' THEN '라이언'
  WHEN 'sam' THEN '샘'
  WHEN 'thomas' THEN '토마스'
  WHEN 'timmy' THEN '티미'
  WHEN 'toby' THEN '토비'
  WHEN 'toma' THEN '토마'
  WHEN 'tom' THEN '톰'
  WHEN 'travis' THEN '트래비스'
  WHEN 'valiant' THEN '발리언트'
  WHEN 'victor' THEN '빅터'
  WHEN 'vince' THEN '빈스'
  WHEN 'william' THEN '윌리엄'
  ELSE voice_data->>'name'  -- 매핑이 없으면 원본 name 사용
END
WHERE (name_ko IS NULL OR name_ko = '' OR name_ko = voice_id)
  AND voice_data->>'name' IS NOT NULL
  AND voice_data->>'name' != ''
  AND (voice_data->>'name' !~ '[가-힣]');  -- 한글이 아닌 경우만

-- 업데이트 결과 확인 (선택사항)
-- SELECT voice_id, name_ko, voice_data->>'name' as voice_data_name,
--   CASE WHEN name_ko IS NULL OR name_ko = '' THEN '업데이트 필요' ELSE '완료' END AS status
-- FROM public.tts_voice_catalog
-- WHERE name_ko IS NULL
-- ORDER BY voice_id;

